services:
  _defaults:
    autowire: true
    autoconfigure: true

  Security\:
    resource: '%kernel.project_dir%/src/Security/*'

  Security\Application\Command\CreateAUser\CreateAUserCommandHandler:
    arguments:
      $repository: '@Core\Repository\EventStoreRepository'
    tags:
      - { name: broadway.command_handler }

  Security\Infrastructure\Repository\DBAL\DBALRepositoryFactory:
    public: true
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@broadway.serializer.readmodel'
