services:
  _defaults:
    autowire: true
    autoconfigure: true

  Security\:
    resource: '%kernel.project_dir%/src/Security/*'

  Security\Application\Command\CreateAUser\CreateAUserCommandHandler:
    arguments:
      $repository: '@user_event_store_repository'
    tags:
      - { name: broadway.command_handler }

  user_event_store_repository:
    class: Core\Repository\EventStoreRepository
    arguments:
      - '@broadway.event_store'
      - '@broadway.event_handling.event_bus'
      - 'Security\Domain\AggregateRoot\User'
