services:
  _defaults:
    autowire: true
    autoconfigure: true

  Core\:
    resource: '%kernel.project_dir%/src/Core/*'

  Core\Repository\ReadModelRepository\DBALReadModelRepositoryFactory:
    arguments:
      $serializer: '@broadway.simple_interface_serializer'

  Core\Repository\EventStoreRepository:
    arguments:
      - '@broadway.event_store'
      - '@broadway.event_handling.event_bus'
