imports:
    - { resource: '../src/Security/Infrastructure/Config/config.yaml' }

parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App/*'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Shared\Http\Rest\Listener\OnErrorListener:
        tags: [ kernel.event_listener ]

    App\Security\Http\Rest\:
        resource: '%kernel.project_dir%/src/App/Security/Http/Rest/*'
        tags: [ 'controller.service_arguments' ]

    App\Security\Projector\DoctrineUserProjector:
        tags:
            - { name: broadway.domain.event_listener }

    App\Shared\Adapter\CommandBus:
        arguments:
            - "@broadway.command_handling.command_bus"
